dist: trusty
sudo: false
git:
  depth: false
env:
  global:
    - CC_TEST_REPORTER_ID=53eef44d00d3465aeaf806ea310cfc5497e7473d13ae05fbc753890c39712c60
addons:
  sonarcloud:
    organization: "lucacappelletti94-github"
    token:
      secure: "ilZifYjhh1qTXnYbNlIoqL9ddwIBCS1k9A/T1yTv+k4L/UgJLSsBBkTPF6YxLR1VHfvwL2yL6mSzuol399wnGc6e//jiijeKS9g8Iaf1jreqDxrS5Nyjnvgn7NAfevSUD0MLhOJAUGHtx3KrN5RMzwoVVW7v3pLEsEE9ObOgp3MX0MaA/roBdXNkGP2tgiVSc6r1s07Oa8XkJvI9l9Ms6eR4RzkE162+W5vD7pMNo6KmuDeUR0bZrSUsngFaezlUp61E9RV2/+bMabm3awBgC4LnrmtsIKkMZbFrlxa9s019K1iWit6R5U2iDHByhiseifmHWpsnZ/LVlOm7yOBIT5Cm9PFemK9gD5ubKjSBITsB30lJC4wKVVBlMUWQpS1ofRS6hyjuvqLd0opIjpfaxBtur63HWuS+c28RDjCUyVZTTxSllFsDzV1Secp19Bv1nJxt1cs4iWbGzlwH9OzHISw4vDDNvO/C1kwHMMGSUNU5OU7SOuMvK/yv+aGRr4xG8tdS05r1X1Y0Vv4JEWLL1xbFv//h9o7el0OUqmbXsUuBaQTXfwI3WnmbsM/dUbtqW8tCnz9pmVI7GsASp0yvSx+jReE7U2WWFL1Sra8K/P1OpJFS2r2eiF6GvhU9mdZGDeepXNUQqLGXt2V6hYTeL/cTrFoONv9gZ/vm/PfjJsc="
language: python
python:
- '3.6'
before_install:
  - pip install --upgrade pytest
install:
- pip install .[test]
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=deflate_dict --cov-report xml:coverage.xml 
- coverage report
- coverage xml
- sonar-scanner

after_success:
  - coveralls

notifications:
  email: false
