dist: trusty
sudo: false
git:
  depth: false
addons:
  sonarcloud:
    organization: lucacappelletti94-github
    token:
      secure: "+HC8LaDiGGNl8W6OPfCQ4fG7kpAxqwEuWL/vg2usbeQ5wGT7OTwlbLnN3X1JL8bXijqcm3EMtZsMhSCJcq1GMQCopJLLNqZuNWUSca1GXvout8E/EaU9aNFwfen9yGRPOm260l3mWbs06jyv2TooszKYvD//qoiHvSXXBG3mlusVp/e7P6OaenKzUGvF3N9nDuV2LhdMptDdUA98EzQWVrNjWpKI5jMpkVAABlF5Mtb74d8mrCw1DctdchQxYB18WiUmTK/Nq5Jg86HnG8NnN+fgg1diSA0R0LJvs2+nvHujnaXVq5QiXBT3iQ8BCzE5rNMkY3fq8SlqHtxn6prTEXLPbRijaD87DO0T2aO/sEShJMSCnegFaHy8ti1g6/2M1Mox78pnYaW4u4oMnORLkENMlhAL7XEkUE0lMA3rPNsBDSgFlFnJvo7b5yQy8lBLMWCzl/Yp1jy7uUFJaBRPU+fkYGM/d+zp8d+348BHqc0EGotom+cBIK1SZ14KJM2KOuRic7On44u6r06dyY/cBxP13txkqGdijjY9yn0CexA4w69qbNNfLnDefNZr33fYOAkLs+YQ+nOpX7H9ylP3iwVth+A35fSRVRYSUPuXLMJa0muVKs+gZo1U+y/wqqY1P96RvSooJgwALqQQpe+D3YpYq4EdvnfE8DTbQTIS1e8="
language: python
python:
- '3.6'
before_install:
- pip install --upgrade pytest
install:
- pip install .[test]
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=deflate_dict --cov-report xml:coverage.xml
- coverage combine --append || true
- coverage report
- coverage xml
- sonar-scanner
after_success:
- coveralls
- python-codacy-coverage -r coverage.xml
env:
  global:
  - secure: o9v/135PMDpk9jpmirMJKfXb/GWQRb0lXyqP8+QxpIIkF4G3+0uF8znGBuFr5Jn/2UePCc16eWKcseFbBw3RIrZ8xLtC9E6BmO9DsVeS7chfPMbKtKX7lq+GZCSugoBj4EqfOBDJbGc02uoT+4c7yxSxU4pjLqPTOgmFlS6lM0I8xzuVv8FP8Hxd4KOKuOdrPTD0k1ilUNP5+JaQPXeCsXJQ4ew8C43Uj5tCezZbUnMAG4AQTXFjjtt8uM2Jn4qaBSezjM1czDYjD7XYB+1wgWDv+gtvOCbTnIdckiq1jvg92vaN9Y9oLEEmyLPiZwUW3LbHJnv4Kqpkdg8pEPjNZGbvfp9d7+zo54GUyhEAZ0LpaoZrKU/7bKG7M9IgJL9Qr+v8+6oqyiuuG+1NITrcSffNfIJpSqxSfhWE6DoCm1cHcODpUljxXpoLXoTU9eXBuPQH/snG8/pj6Qrm2tYWAsYvPXEBwKB9WMNS5f8kqbbQGFiaj7LCHmRcGVBlaMLZ3FgEKz2Ht+yfkfDRtvEt6Q6M7H7Gm45OVSzsduD9rynxUWwnZH2VQKS8TIQqteLYok5uKcyMuk/FhX6d3cvl+RkU5Lzxk6D1AbFKHFuOOzO8VOZhJ6APfwXAdHTyC3wsqAlNDu2TZbdLLTNoOQq/I62T4mZdif8FKcpfyD8YG0M=
  - secure: zZFmVZLK1I5sgLpCtqG4ar+p/vtG5INPITElZ8RpH5wXGyJ4ATQa/br6LAN4UgDMPZy2O0XXSGFusaVG3JKtT6GgZ3VVjkTCUghkfFrwYOgN0LDSW+PmhBw1xLKeFzz7TYYSb76hiyHh1pQk0I7j5eC6Ac+LO86vE04WG9F817zh5JSEpmYXMWDPfSdhA3QWkZt9TnTptDIqEvP9JaFt5DuFPS4u6lmfSDAilouy/Bwt3gOkxfvJv7sslBDKoVLjipc1Ke2GlZnLLxUUYua/2P/CoZaY4GMtTub5R/CHeTUH6RBXz1HWWzUkx9gfoK/xd2i5AQRRb4O30pB6WQZMJtCFXTLYzCkEiADmsD1AyeSqXfLL/vjX/ZbgJvfqJYurbw8cpv/EFW0IHluN2IOkii5Ty0iQ/6h1rqkk/FvgAGCNStVwIm2//bhYw5UvtAKe+UACY/FeqHNSn3xwi64REZTl6QYco2/FQQy7cutFtiLY9p7rwHGB2UKG15FYBO6MNfbKNXvIFp6ZpABGBBHj7C6HpdYBqSx1VFMdCOrar5ER+n4eRpyawAfQFT/Uf+cfk27ueLGFJS93i2tOGD2BS6R3LTJAgvP37n/Ibxer578HQ8/L7cMPoZqBjzKWxJ+blXis0qRrc7L/3GpOy8vDMWuuYC3wmnW2EnFk07Vh0Vg=
